### ISSUE TITLE
Add a drill hole below where the boost pads sits

### ISSUE THREAD

**Issue by Nestpebble** [gargomoma/fakeTec_pcb#2]
Hey, could you add a little hole underneath the boost pads, please? It's sort of shown in this drawing:
https://discord.com/channels/867578229534359593/1194757507013427250/1272294175194222593

I've also made a footprint in the EasyEDA library that shows it - I'll find a link a bit later on.

**Comment by lupusworax** [comment]
I would also love to see  that happen, please  please please! It would make things a lot easier.

**Comment by lupusworax** [comment]
Amazing! Thanks for updating the design, the reset an function button is a perfect upgrade also the cutout, I ordered right away.  With the updated HT-RA62 modules now finally working reliable the faketec is going to be total success story for sure!

**Comment by Nestpebble** [comment]
Yep - all looks good to me!
